[tool.black]
skip-magic-trailing-comma = true
target-version = ["py310"]

[tool.isort]
case_sensitive = true
profile = "black"

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "-vv --durations=10 --cov=archon --cov-branch"
