name: Test

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  MYPYPATH: /tmp/typehints
  SC_ORIGIN: https://github.com/supercollider/supercollider.git
  SC_BRANCH: develop

jobs:

  cancel:
    name: Cancel previous workflow
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  lint:
    name: Lint
    needs: [cancel]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install Python requirements
      run: pip install -e .[test]
    - name: Install mypy from master (need https://github.com/python/mypy/pull/13397)
      run: pip install https://github.com/python/mypy/archive/refs/heads/master.zip
    - name: Install Archon
      run: pip install -e .[test]
    - name: Get Type Hints
      run: |
        pip install --target /tmp/typehints --no-deps supriya
        pip install --target /tmp/typehints --no-deps uqbar
    - name: Black
      run: make black-check
    - name: Flake8
      run: make flake8
    - name: Mypy
      run: make mypy

  test:
    name: Test
    needs: [cancel]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install APT packages
      run: sudo apt-get install -y libsndfile1
    - name: Install Archon
      run: pip install -e .[test]
    - name: Install SuperCollider
      uses: ./.github/actions/supercollider
      with:
        branch: ${{ env.SC_BRANCH }}
        origin: ${{ env.SC_ORIGIN }}
    - name: Test
      run: make pytest
